export enum ServiceDuration {
  FIFTEEN_MINUTES = 15,
  THIRTY_MINUTES = 30,
  SIXTY_MINUTES = 60,
}

export enum ServiceType {
  DOCTOR = "DOCTOR",
  CONSULTANT = "CONSULTANT",
  SUPPORT_AGENT = "SUPPORT_AGENT",
  THERAPIST = "THERAPIST",
  TECHNICIAN = "TECHNICIAN",
}
